from config import DEFAULT_LANGUAGE

TEXTS = {
    "en": {
        "language_choose": "Choose your language:",
        "language_saved_en": "Language set: English",
        "language_saved_ru": "Language set: Russian",
        "main_menu": "Main menu:",
        "habits_menu": "Habits:",
        "tasks_menu": "Tasks:",
        "finance_menu": "Finance:",
        "btn_habits": "📅 Habits",
        "btn_tasks": "📝 Tasks",
        "btn_finance": "💸 Finance",
        "btn_back": "⬅ Back",
        "btn_add": "➕ Add",
        "btn_list": "📋 List",
        "btn_done": "✔ Done",
        "btn_goal": "🎯 Goal",
        "btn_stats": "📊 Stats",
        "btn_income": "➕ Income",
        "btn_expense": "➖ Expense",
        "addhabit_prompt": "Enter habit name:",
        "habit_added": "Habit added: {name}",
        "done_no_habits": "No habits.",
        "done_select": "Which habit?",
        "done_success": "Marked.",
        "list_header": "Your habits:",
        "list_line": "{id}. {name} — 🔥 {streak}",
        "goal_select": "Select habit:",
        "goal_enter": "Enter weekly goal:",
        "goal_saved": "Saved.",
        "habitstats_header": "Habit statistics:",
        "habitstats_line": "{name}: streak {streak}, goal {goal}",
        "task_title": "Task title:",
        "task_due": "Deadline ('-' for none):",
        "task_added": "Task added.",
        "task_list_header": "Your tasks:",
        "task_open": "{id}. {title} — due: {due}",
        "task_done_line": "{id}. ✔ {title}",
        "task_done_select": "Which task?",
        "task_done_success": "Task completed.",
        "fin_amount": "Amount:",
        "fin_category": "Category:",
        "fin_note": "Note ('-' for none):",
        "expense_added": "Expense added.",
        "income_added": "Income added.",
        "fin_stats_header": "Finance stats:",
        "fin_stats_line": "{category}: {amount}",
        "fin_balance": "Income: {income}\nExpense: {expense}\nBalance: {balance}",
    },

    "ru": {
        "language_choose": "Выберите язык:",
        "language_saved_en": "Language set: English",
        "language_saved_ru": "Язык установлен: Русский",
        "main_menu": "Главное меню:",
        "habits_menu": "Привычки:",
        "tasks_menu": "Задачи:",
        "finance_menu": "Финансы:",
        "btn_habits": "📅 Привычки",
        "btn_tasks": "📝 Задачи",
        "btn_finance": "💸 Финансы",
        "btn_back": "⬅ Назад",
        "btn_add": "➕ Добавить",
        "btn_list": "📋 Список",
        "btn_done": "✔ Выполнено",
        "btn_goal": "🎯 Цель",
        "btn_stats": "📊 Статистика",
        "btn_income": "➕ Доход",
        "btn_expense": "➖ Расход",
        "addhabit_prompt": "Введите название привычки:",
        "habit_added": "Добавлено: {name}",
        "done_no_habits": "Нет привычек.",
        "done_select": "Какая привычка?",
        "done_success": "Отмечено.",
        "list_header": "Ваши привычки:",
        "list_line": "{id}. {name} — 🔥 {streak}",
        "goal_select": "Выберите привычку:",
        "goal_enter": "Введите цель:",
        "goal_saved": "Сохранено.",
        "habitstats_header": "Статистика:",
        "habitstats_line": "{name}: стрик {streak}, цель {goal}",
        "task_title": "Название задачи:",
        "task_due": "Срок ('-' если нет):",
        "task_added": "Задача добавлена.",
        "task_list_header": "Ваши задачи:",
        "task_open": "{id}. {title} — срок: {due}",
        "task_done_line": "{id}. ✔ {title}",
        "task_done_select": "Какая задача?",
        "task_done_success": "Готово.",
        "fin_amount": "Сумма:",
        "fin_category": "Категория:",
        "fin_note": "Комментарий ('-' если нет):",
        "expense_added": "Расход добавлен.",
        "income_added": "Доход добавлен.",
        "fin_stats_header": "Финансовая статистика:",
        "fin_stats_line": "{category}: {amount}",
        "fin_balance": "Доход: {income}\nРасход: {expense}\nБаланс: {balance}",
    }
}

def t(lang, key, **kw):
    txt = TEXTS.get(lang, TEXTS[DEFAULT_LANGUAGE]).get(key, key)
    return txt.format(**kw) if kw else txt
